default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: one_cafe_search_development

test:
  <<: *default
  database: one_cafe_search_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>