default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: one_cafe_search_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>